name: invalidate-landing

on:
  push:
    branches:
      - main
    paths:
      - "landing/**"
      - ".github/workflows/landing.yml"


defaults:
  run:
    working-directory: landing

jobs:
  invalidate:
    runs-on: ubuntu-latest

    steps:
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Run cache invalidation for index.html
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/landing/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
